# https://render.com/docs/preview-environments
previewsEnabled: true
previewsExpireAfterDays: 3

services:
  - type: web
    name: toolpad-app
    env: docker
    dockerfilePath: ./docker/images/toolpad/Dockerfile
    dockerContext: ./
    plan: starter plus
    numInstances: 1
    healthCheckPath: /health-check
    envVars:
      - key: TOOLPAD_DATABASE_URL
        fromDatabase:
          name: toolpad-db
          property: connectionString
      - fromGroup: toolpad-settings

databases:
  - name: toolpad-db
    ipAllowList: []
    plan: starter
    previewPlan: starter

envVarGroups:
  - name: toolpad-settings
    envVars:
      - key: TOOLPAD_BASIC_AUTH_USER
        sync: false
      - key: TOOLPAD_BASIC_AUTH_PASSWORD
        sync: false
